export const inputFields = [
    { label: "Phân loại MS", inputField: "msSubClass" },
    { label: "Chiều dài lô đất", inputField: "lotFrontage" },
    { label: "Diện tích lô đất", inputField: "lotArea" },
    { label: "Chất lượng tổng thể", inputField: "overallQual" },
    { label: "Tình trạng tổng thể", inputField: "overallCond" },
    { label: "Năm xây dựng", inputField: "yearBuilt" },
    { label: "Năm sửa chữa/thêm mới", inputField: "yearRemodAdd" },
    { label: "Diện tích gạch/đá", inputField: "masVnrArea" },
    { label: "Tầng hầm hoàn thiện 1", inputField: "bsmtFinSF1" },
    { label: "Tầng hầm hoàn thiện 2", inputField: "bsmtFinSF2" },
    { label: "Tầng hầm chưa hoàn thiện", inputField: "bsmtUnfSF" },
    { label: "Tổng diện tích tầng hầm", inputField: "totalBsmtSF" },
    { label: "Diện tích tầng 1", inputField: "firstFlrSF" },
    { label: "Diện tích tầng 2", inputField: "secondFlrSF" },
    { label: "Diện tích hoàn thiện thấp", inputField: "lowQualFinSF" },
    { label: "Diện tích sinh hoạt", inputField: "grLivArea" },
    { label: "Phòng tắm đầy đủ tầng hầm", inputField: "bsmtFullBath" },
    { label: "Phòng tắm nửa tầng hầm", inputField: "bsmtHalfBath" },
    { label: "Phòng tắm đầy đủ", inputField: "fullBath" },
    { label: "Phòng tắm nửa", inputField: "halfBath" },
    { label: "Phòng ngủ", inputField: "bedroomAbvGr" },
    { label: "Nhà bếp", inputField: "kitchenAbvGr" },
    { label: "Tổng số phòng", inputField: "totRmsAbvGrd" },
    { label: "Lò sưởi", inputField: "fireplaces" },
    { label: "Năm xây gara", inputField: "garageYrBlt" },
    { label: "Số xe trong gara", inputField: "garageCars" },
    { label: "Diện tích gara", inputField: "garageArea" },
    { label: "Diện tích sàn gỗ", inputField: "woodDeckSF" },
    { label: "Diện tích hiên mở", inputField: "openPorchSF" },
    { label: "Diện tích hiên kín", inputField: "enclosedPorch" },
    { label: "Diện tích hiên 3 mùa", inputField: "threeSsnPorch" },
    { label: "Diện tích hiên lưới", inputField: "screenPorch" },
    { label: "Diện tích bể bơi", inputField: "poolArea" },
    { label: "Giá trị khác", inputField: "miscVal" },
    { label: "Tháng bán", inputField: "moSold" },
    { label: "Năm bán", inputField: "yrSold" },
];